import { DM_Mono } from "next/font/google";
import "./globals.css";

const inter = DM_Mono({ weight: ["300", "400", "500"], subsets: ["latin"] });

export const metadata = {
  title: "Moia",
  description: "Generated by Moia",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
